---

- hosts: ubuntu.my
  become: yes
  tasks:
  - name: Установка пакетов
    apt: name={{item}} state=latest
    with_items:
      - mysql-server
      - mysql-client
      - wordpress
      - libapache2-mod-php
      - php-mysql
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl
      - php-zip
